version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: github.com/Microsoft/go-winio
    versions:
    - 0.4.16
    - 0.4.17
    - 0.4.18
    - 0.4.19
