run:
    deadline: 3m
    issues-exit-code: 1
    tests: true
    build-tags:
    - integration

linters:
    enable:
    - deadcode
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - megacheck
    - misspell
    - structcheck
    - varcheck
    disable:
    - typecheck # temporary because of Go 1.11 incompatiblity

linters-settings:
    lll:
        tab-width: 8
