exclude: '^vendor/'
repos:
-  repo: local
   hooks:
   -  id: vet
      name: go vet
      language: system
      entry: go vet  ./...
      pass_filenames: false
      types: [go]
   -  id: lint
      name: golangci
      language: system
      entry: golangci-lint run
      pass_filenames: false
      types: [go]
   -  id: gocritic
      name: gocritic
      language: system
      entry: gocritic check-project -enable=all -withExperimental -withOpinionated -disable boolFuncPrefix,importShadow,unexportedCall .
      pass_filenames: false
      types: [go]
   -  id: revive
      name: revive
      language: system
      entry: revive -exclude ./vendor/... ./...
      pass_filenames: false
      types: [go]
