language: go
os: osx
go:
 - "1.11.x"
env:
 - GO111MODULE=on
addons:
  homebrew:
    packages: watchman
install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/fzipp/gocyclo
  - go get -t -v ./...
script: make test
