[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.11"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
