[[constraint]]
  name = "github.com/Microsoft/go-winio"
  version = "0.4.9"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fortytw2/leaktest"
  version = "1.2.0"
